# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: er妞的博客
email: erbao.wang@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://web1992.cn" # the base hostname & protocol for your site
#twitter_username: web1992
github_username:  web1992
description: "京ICP备15055486号<br /> 
	      jekyll 3.0.1<br />
"
# Build settings
markdown: kramdown
